### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain'

### ISSUE THREAD

**Issue by orenplevin** [Open-Swarm-Net/GPT-Swarm#15]
Sounds like a great project would love for it to work....

**Describe the bug**
After entering the keys in keys.json
Typed to run - ./run.sh start

python: can't open file '/Users/xxx/Documents/GPT/GPT-Swarm/scripts/check_requirements.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/xxx/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/Documents/GPT/GPT-Swarm/swarmai/__main__.py", line 7, in <module>
    from swarmai.Swarm import Swarm
  File "/Users/xxx/Documents/GPT/GPT-Swarm/swarmai/Swarm.py", line 14, in <module>
    from swarmai.utils.memory import VectorMemory
  File "/Users/xxx/Documents/GPT/GPT-Swarm/swarmai/utils/memory/__init__.py", line 1, in <module>
    from .VectorMemory import VectorMemory
  File "/Users/xxx/Documents/GPT/GPT-Swarm/swarmai/utils/memory/VectorMemory.py", line 2, in <module>
    from langchain.vectorstores import Chroma
ModuleNotFoundError: No module named 'langchain'
Press any key to continue...

**Comment by nicelir1996** [comment]
fixed with the latest commits: edfddce07d18be358ffc5987d57e579bf206ff3f, 81a778f386c329321e09db35445296c512349f7f

**Comment by nicelir1996** [comment]
hm... strange. Seems like a chromadb problem: https://github.com/pypa/packaging-problems/issues/648

Seems like it needs the c++ compiler. Since you are on mac, follow this: http://cs.millersville.edu/~gzoppetti/InstallingGccMac.html
or you can also try `xcode-select --install`

If this doesn't help:
- Did you recently do something with the default gcc compiler? Could you please run and post here: `gcc --version`, `which gcc`
- Also describe your environment: `python3 --version` and `python3 -m pip list`
- Could you please [describe your mac system](https://osxdaily.com/2022/02/02/find-mac-system-info-terminal-system-profiler/), i'll try to reproduce it.
- you can also try to install the bad package manually `pip3 install hnswlib`
- in general, just in case, i recommend using either conda or a virtual environment with a give requirements.txt to make sure that there is no clash between packages (the newest langchain version breaks chroma for example)
